### ISSUE TITLE
Add Roku Channel for Bad Voltage, please.

### ISSUE THREAD

**Issue by 3rdwiki** [badvoltage/roku-app#1]
The BadVoltage Channel needs to viewed on the Official Roku Downloadable channels.

This is to kickstart the whole process, kindly adopted by @stuartlangridge 

Please leave comments and amendments below, thank-you.

**Comment by 3DJetengine** [comment]
@flexiondotorg thank-you & have a hat-tip in return: https://v.gd/8P220z
